---
# For complete list of options see https://aquasecurity.github.io/tfsec/v0.63.1/getting-started/configuration/config/

# The minimum tfsec version to be used
min_required_version: v1.26.3

# The minimum severity of result that should be reported. By default, every severity is reported. 
# You must use one of CRITICAL, HIGH, MEDIUM, LOW.
minimum_severity: LOW
